### ISSUE TITLE
Add 'contacts' model

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-aux#26]
Attributes: slug (or code), name, short_name, url, phone, email, ask

**Comment by coblej** [comment]
Currently implemented based on YAML file in Ddr::Models::Contacts

**Comment by coblej** [comment]
@dchandekstark Unless you think this is a bad idea, this might be a good opportunity for me to learn how to do one of these ddr-aux things.

**Comment by dchandekstark** [comment]
Sure!
